name: Python Test

on:
  push:
    branches: [ main, feature/*, hotfix/*, release/* ]
  pull_request:
    branches:
      - '*'

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f test-requirements.txt ]; then pip install -r test-requirements.txt; fi
    - name: Check
      run: |
        # stop the build if there are Python syntax errors or undefined names
        inv check
    - name: Test
      run: |
        inv test